inherit_from: .rubocop_todo.yml
require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails
  - rubocop-capybara

Rails:
  Enabled: true

AllCops:
  NewCops: enable
  DefaultFormatter: progress
  DisplayCopNames: true
  Exclude:
    - .gem/**/*
    - bin/**/*
    - build/**/*
    - deploy/**/*
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*
    - gems/**/*
    - log/**/*
    - node_modules/**/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*
    - .pryrc

  # Set cache directory inside project root.
  # This will speed up rubocop being run with docker-compose
  CacheRootDirectory: tmp/

Metrics/MethodLength:
  Max: 20
  Exclude:
    - lib/book_parser.rb

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - lib/book_parser.rb
    - config/routes.rb
    - config/environments/*.rb
    - spec/**/*.rb
    - lib/tasks/**/*.rake

Metrics/AbcSize:
  Exclude:
    - lib/book_parser.rb
    - app/sidekiq/generate_embeddings_job.rb

RSpec/ExampleLength:
  Max: 15

Metrics/ClassLength:
  Exclude:
    - app/controllers/api/v1/questions_controller.rb

# Checks if example groups contain too many `let` and `subject` calls.
RSpec/MultipleMemoizedHelpers:
  Enabled: false
